name: 'Autom. "build-node" ausführen'

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  build-node:
    runs-on: ubuntu-latest
    container: node:14
    steps:
      - run: node --version
      - run: npm --version
      - run: npm ./retrowfc/stats-liste/update-data.js
